In [2]:
import numpy as np

1. Perform aset of exercises

_Excercise 6_. An array is entered from the keyboard. Replace all non-zero elements with -1

In [3]:
def ex6(arr):
    arr[arr != 0] = -1
    return arr
a = np.array([int(i) for i in input(": ").split()])
print(ex6(a))

: 5 6 -1 0 0 2 1 3
[-1 -1 -1  0  0 -1 -1 -1]


_Excercise 9_. Enter the number _n_. Create an array of values from _n_ to 0.

In [4]:
def ex9(n):
    return np.arange(n,-1,-1)
n = int(input(": "))
print(ex9(n))

: 111
[111 110 109 108 107 106 105 104 103 102 101 100  99  98  97  96  95  94
  93  92  91  90  89  88  87  86  85  84  83  82  81  80  79  78  77  76
  75  74  73  72  71  70  69  68  67  66  65  64  63  62  61  60  59  58
  57  56  55  54  53  52  51  50  49  48  47  46  45  44  43  42  41  40
  39  38  37  36  35  34  33  32  31  30  29  28  27  26  25  24  23  22
  21  20  19  18  17  16  15  14  13  12  11  10   9   8   7   6   5   4
   3   2   1   0]


_Excercise 10_. Enter the numbers _n_ and _m_. Create an array of random values of size _n_х_m_ and calculate the minimum,  maximum value, mean and standard deviation, rounded to 3 decimal places

In [25]:
def ex10(n,m):
    arr = np.random.random((n,m))
    print(arr.max())
    print(arr.min())
    print(arr.mean())
    print(arr.std())
ex10(5,5)

0.9426687015371893
0.014200075098755316
0.4386051248640602
0.2665905870092382


Excercise 11. Create an array of 1 of size _n_х_n_ and add to it a "border" formed from 0

In [27]:
def ex11(n):
    arr = np.ones((n,n), dtype=int)
    arr[0]=0
    arr[-1]=0
    arr[:,0]=0
    arr[:,-1]=0
    return arr
print(ex11(10))

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


Excercise 15. Arrange 1 and 0 on the 8х8 field in a checkerboard pattern using the numpy _tile_().

In [28]:
def ex15():
    return np.tile([0,1], (8,8))
print(ex15())

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


Excercise 18. Fill the vector with values from 0 to _n_. Replace signs for all values less than _n_/2 and greater than _n_/4 to opposite ones.

In [32]:
def ex18(n):
    arr = np.arange(0,n+1)
    arr[(arr < n/2) ^ (arr > 3*n/4)] *= -1
    return arr
print(ex18(10))

[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]


Excercise 19. Generate  a  vector  of _n_ random  numbers  in  the  range  from  0  to  99. Determine the number of unique elements in the sequence.

In [61]:
def ex19(n):
    arr = np.random.randint(0,100,(n,))
    ues = np.unique(arr).size
    return arr, ues
for r in ex19(100): 
    print(r)

[12 43 26 40 84 59 66 93 44 60 23 23 36 48 98  0 50 40 95 10 75 54 29 36
 62 53  9 18 59 39 36 13 55 84 38 55 24  1 45 10 17 91 44 79 15 60 43 62
 96 26 26 81 70 86 44 61 12 48 18 12 73 35 21  0  8 82 90  8 26 66 13  0
 48 35 46 73 91 38 18 74 20 79 48 32 43  7 78 87 12 73 12 33 90 18 85 49
 74 39 87 75]
57


Excercise 20. Generate  a  vector  of _n_ elements  that  are  evenly  spaced  on  the interval (0,1), i.e. both ends of the interval are not included. Output values up to 3 decimal places.

In [70]:
def ex20(n):
    arr = np.linspace(0,1,n)[1:-1]
    return arr
print(ex20(10))

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


Excercise 21. Generate a vector of  _n_ random elements, lying in the interval (0,1). Replace the maximum element with 0.

In [73]:
def ex21(n):
    arr = np.random.random(n)
    arr1 = np.where(arr == arr.max(), 0, arr)
    return arr, arr1
for a in ex21(10):
    print(a)

[0.97754202 0.52112997 0.51913879 0.25256484 0.80514614 0.16894982
 0.99440619 0.38606215 0.64442116 0.15755518]
[0.97754202 0.52112997 0.51913879 0.25256484 0.80514614 0.16894982
 0.         0.38606215 0.64442116 0.15755518]


2. Solve the system of linear equations using Cramer's formulas and perform a test using matrix multiplication and _numpy.linalg.solve_().

$$
 \begin{cases}
   2x_1+x_3+4x_4=9 
   \\
   x_1+2x_2-x_3+x_4=8
   \\
   2x_1+x_2+x_3+x_4=5,
   \\
   x_1-x_2+2x_3+x_4=-1
 \end{cases}
$$

In [117]:
def solve_by_cramer(mA, b):
    n = mA.shape[0]
    det = np.linalg.det(mA)
    xs = np.empty(n)
    if det == 0:
        return None
    for i in range(n):
        mAi = np.copy(mA)
        mAi[:, i] = b
        xs[i] = np.linalg.det(mAi) / det
    return xs

a = np.array([[2,0,1,4],[1,2,-1,1],[2,1,1,1],[1,-1,2,1]])
b = np.array([9,8,5,-1])
roots = solve_by_cramer(a, b)
print(roots)
print(np.linalg.solve(a,b))
ax = np.dot(a,roots)
print(ax)
print(np.allclose(ax, b))

[ 1.  2. -1.  2.]
[ 1.  2. -1.  2.]
[ 9.  8.  5. -1.]
True


3. Calculate the value of the matrix expression

\begin{equation}
A(2A+B)-B(A-B), A = \begin{pmatrix} 2 & 3 & 1  \\ 4 & -1 & 0 \\ 0 & 1 & 2 \end{pmatrix}, B= \begin{pmatrix} 9 & 8 & 7 \\ 2 & 7 & 3 \\ 4 & 3 & 5\end{pmatrix}
\end{equation}

In [116]:
def calc(mA, mB):
    res = (mA@(mA*2+mB))-(mB@(mA-mB))
    return res

a = np.array([[2,3,1],[4,-1,0],[0,1,2]])
b = np.array([[9,8,7],[2,7,3],[4,3,5]])
print(calc(a,b))

[[135 171 135]
 [ 54 123  75]
 [ 60  69  69]]


4. Solve the matrix equation using an inverse matrix and perform a test using matrix multiplication and _numpy.linalg.solve_().

\begin{equation}
    \begin{pmatrix} 
    5 & 3 & -1 \\ 2 & 0 & 4 \\ 3 & 5 & -1
    \end{pmatrix}
    *X=
    \begin{pmatrix}
        1 & 4 & 16 \\ -3 & -2 & 0 \\ 5 & 7 & 2
    \end{pmatrix}
\end{equation}

In [121]:
def solve_by_inv(mA, mB):
    if np.linalg.det(mA) == 0:
        return None
    xs = np.linalg.inv(mA) @ mB
    return xs

a = np.array([[5,3,-1],[2,0,4],[3,5,-1]])
b = np.array([[1,4,16],[-3,-2,0],[5,7,2]])
roots = solve_by_inv(a,b)
print(roots)
print(np.linalg.solve(a,b))
prod = a @ roots
print(prod)
print(np.allclose(prod,b))

[[-0.67647059 -0.11764706  4.35294118]
 [ 1.32352941  1.38235294 -2.64705882]
 [-0.41176471 -0.44117647 -2.17647059]]
[[-0.67647059 -0.11764706  4.35294118]
 [ 1.32352941  1.38235294 -2.64705882]
 [-0.41176471 -0.44117647 -2.17647059]]
[[ 1.  4. 16.]
 [-3. -2.  0.]
 [ 5.  7.  2.]]
True
